### ISSUE TITLE
LandPurchase Issues

### ISSUE THREAD

**Issue by MargaretHowe** [Earth42/utopia42-unity#78]
![landbuyfailed](https://user-images.githubusercontent.com/104603161/187789017-9ce63680-3b51-49c1-807f-bfa42d3ba81d.png)
![errorbuyingland](https://user-images.githubusercontent.com/104603161/187789018-edb8be52-c21d-46dd-abf8-7ebf995820ba.png)
![buy1](https://user-images.githubusercontent.com/104603161/187789022-e5e887cc-ce4d-4727-84bb-da0f4ce15c79.png)
![landbuywhat](https://user-images.githubusercontent.com/104603161/187789025-339281b3-83da-4750-b16c-871989f7d309.png)
I tried to buy land. First of all, it failed and here are errors.
Then I came back later and tried to buy more land. This time the transaction went through, but it did not buy the land I drew on the map. Some weird transaction to Matt occurred. @rasoulMrz @bakhshandeh

**Comment by mezamashii** [comment]
My other land purchase did go through, I just didn't wait to reload long enough probably. But look when I try to buy land:
![alliancemattcontract](https://user-images.githubusercontent.com/104603161/187859404-470d6ce5-b99d-41ff-bf18-ab3a40faeb77.png)
Why is land purchase going to Matt's wallet?
